### ISSUE TITLE
equal / hashCode inconsistencies around Array

### ISSUE THREAD

**Issue by eed3si9n** [sbt/contraband#119]
@smarter reports on zinc-contrib Gitter:

> Observe: https://github.com/sbt/zinc/blob/1.x/internal/compiler-interface/src/main/contraband-java/xsbti/api/Path.java
`equals` uses `Arrays.deepEquals` to compare arrays, but `hashcode` uses the regular array `hashCode` instead of `Arrays.deepHashCode`.

This could have severe consequence since you could end up with different `hashCode` while equal returning `true`.

**Comment by smarter** [comment]
Sometimes I wish GitHub had :scream: as a reaction emoji.
