### ISSUE TITLE
always use \n for line breaks

### ISSUE THREAD

**Issue by OlegYch** [sbt/contraband#122]
system-dependent code generation screws up diffs if the generated files are kept in vcs, like in https://github.com/sbt/librarymanagement

**Comment by dwijnand** [comment]
do you know much about .gitattributes? I see it often has things about line break things. do you know if using that would help?

**Comment by dwijnand** [comment]
ok let's default to system line.separator/file.separator and provide contraband-specific overrides.

**Comment by eed3si9n** [comment]
In https://github.com/sbt/contraband/pull/147#issuecomment-612940631 @martijnhoekstra wrote

> If they should look the same as coded by hand, that's going to differ from person to person. I don't think many people use \r\n. Perhaps the line end should align with the most commonly used line end in the contraband file.

I didn't think about it that much but perhaps it's true that for most open source / Scala contributors the editor setting may actually be to use `\n` even on Windows. If so the default being `\n` may be the way to go, with possible configurability to use system default.

**Comment by martijnhoekstra** [comment]
I can't speak for anyone else, but tools making me deal with \r\n on Windows cause me *much* more annoyance and work than tools that just give me \n on Windows.

In this specific example, building sbt changes all contraband generated file in the repo to \r\n line endings. git status gives no useful output anymore, and git commit -a will commit them all with new line endings, so you have manually figure out in a sea of contraband generated files which files to add, or replace all \r\n in .scala files in any contraband directory with \n hoping that there weren't any \r's that were supposed to be there.

That's annoying, but all the more annoying when I know that the \r\n line endings were put there intentionally to be helpful.
