### ISSUE TITLE
The way optional properties are defaulted is wrong

### ISSUE THREAD

**Issue by dwijnand** [sbt/contraband#58]
Previously you could default any optional type like this:

```json
{ "name": "defaultConfiguration", "type": "sbt.librarymanagement.Configuration?", "default": "None", "since": "0.0.1" }
```

Now that generates

```scala
Option(None)
```

as the value in the constructor overload.

Changing the default to blank string (`"default": ""`) generates

```scala
Option()
```

Which is also wrong as Option.apply is defined as:

```scala
def apply[A](x: A): Option[A]
```

**Comment by eed3si9n** [comment]
Yea. That's a breaking change. In the new language, `None` is provided automatically.
I can add special handling for `None` to keep the breakage to minimal.

**Comment by dwijnand** [comment]
We just need regular handling of default, nothing special.

**Comment by eed3si9n** [comment]
http://www.scala-sbt.org/contraband/schema.html#since+annotation

In Contraband the default looks like this:

```scala
type Greeting {
  x: Int = 0 @since("0.2.0")
}
```

**Comment by dwijnand** [comment]
Is the JSON schema unmaintained?

**Comment by dwijnand** [comment]
Should we fix this bug or should I move to the Contraband schema language?

**Comment by eed3si9n** [comment]
It's really up to us. I was saying that the semantics of the default value is now lifted to `Option( + x + )`.

**Comment by eed3si9n** [comment]
Given #60, maybe this is a legitimate bug in my handling of JSON style schema.
