### ISSUE TITLE
The way seq-like properties (Foo*) are defaulted makes it impossible to migrate

### ISSUE THREAD

**Issue by dwijnand** [sbt/contraband#60]
The previous working definition

```json
{ "name": "scalaArtifacts", "type": "String*", "default": "sbt.librarymanagement.ScalaArtifacts.Artifacts", "since": "0.0.1" }
```

no longer works because `sbt.librarymanagement.ScalaArtifacts.Artifacts` is wrapped in a Vector, when it shouldn't be.

**Comment by eed3si9n** [comment]
Let me look at this one. Auto wrapping to Vector probably won't make sense.
