### ISSUE TITLE
The Formats for the last datatype isn't mixed into the cake

### ISSUE THREAD

**Issue by dwijnand** [sbt/contraband#61]
in sbt/librarymanagement the last datatype defined is `UpdateReportLite`, its Formats isn't mixed into `LibraryManagementCodec`.

**Comment by dwijnand** [comment]
Actually it's not just the last one, `UpdateReportFormats` is also missing.

**Comment by dwijnand** [comment]
I guess there are fatal flaws in the implementation of #56 that have caused these regressions.

**Comment by eed3si9n** [comment]
Is your latest schema somewhere on Github or gist?

**Comment by dwijnand** [comment]
https://github.com/dwijnand/sbt-lm/blob/a5b2c141c8e28081b445a6e57cff815082b11300/librarymanagement/src/main/contraband/librarymanagement.json

**Comment by dwijnand** [comment]
Also `ConfigurationReportLiteFormats` and `UpdateConfigurationFormats`

therefore these are missing:

```scala
with sbt.librarymanagement.UpdateReportLiteFormats
with sbt.librarymanagement.UpdateReportFormats
with sbt.librarymanagement.ConfigurationReportLiteFormats
with sbt.librarymanagement.UpdateConfigurationFormats
```
