### ISSUE TITLE
Change the hash code implementation for empty classes

### ISSUE THREAD

**Issue by jvican** [sbt/contraband#86]
From the Zinc API:

```
package xsbti.api;
public abstract class Access implements java.io.Serializable {
    public Access() { super(); }

    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        } else if (!(obj instanceof Access)) {
            return false;
        } else {
            Access o = (Access)obj;
            return true;
        }
    }
    public int hashCode() { return 17; }
    public String toString() {
        return "Access("  + ")";
    }
}
```
  
Empty classes cannot have a constant as the hash code, otherwise all the empty classes are recognised to be the same, when **they are not**.
  
The implementation of hash code should change for this case.

**Comment by eed3si9n** [comment]
I noticed that too recently when I had to manually change the generated code.
We can salt the hash with the hash of the class name.

**Comment by jvican** [comment]
This is an important one for sbt RC I believe. It would be great to get it in the next release to make sure that equality is always safe in the sbt modules. I would not be surprised if we could silently encounter this issue in production...

**Comment by jvican** [comment]
Let me know when you cut a release of this, I'll depend on it in Zinc straight away. It's important that we make sure this bug is not propagated somewhere in our tests.

**Comment by eed3si9n** [comment]
0.3.0-M6 should have this change.

**Comment by jvican** [comment]
@eed3si9n Can you reopen this?
  
It seems that the fix partially addresses this problem since it uses the simple name of the class definition. However, to make sure that no collision ever happens, Contraband should use the FQN (fully qualified name) of the class definition.

**Comment by jvican** [comment]
For more details, see comments in https://github.com/sbt/zinc/pull/331#discussion_r125345303.
